#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ # The URL of the Eureka Server
#    register-with-eureka: true # Whether to register this application with Eureka
#    fetch-registry: true # Whether to fetch the registry from Eureka
#  instance:
#    preferIpAddress: true